# Generated by Django 5.1.3 on 2024-11-10 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_laboratorywork_content_rendered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='independentwork',
            options={'verbose_name': 'Самостоятельная работа', 'verbose_name_plural': 'Самостоятельные работы'},
        ),
        migrations.AlterModelOptions(
            name='laboratorywork',
            options={'verbose_name': 'Лабораторная работа', 'verbose_name_plural': 'Лабораторные работы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='laboratorywork',
            name='content_rendered',
        ),
        migrations.AlterField(
            model_name='laboratorywork',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
