# Generated by Django 5.1.3 on 2024-11-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_links_options_laboratorywork_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='independentwork',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
